"""baseline schema (full current model set)

Adopts Alembic on a project that previously provisioned its schema with
``Base.metadata.create_all``. This baseline builds the entire current schema from
the ORM metadata, so the migration stays perfectly in sync with the models (no
hand-transcription drift). Subsequent schema changes should be captured with
``alembic revision --autogenerate -m "<change>"``.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-21
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401  (kept available for future autogenerated revisions)

from app.database import Base
import app.models  # noqa: F401  — importing the package registers every table on Base.metadata

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    # Create any tables that don't yet exist (idempotent; safe on a DB previously
    # provisioned via create_all — existing tables are skipped).
    Base.metadata.create_all(bind=bind, checkfirst=True)
    # Safety net: databases whose `controls` table predates the `framework` column
    # (added with ISO 27019 support) won't gain it from create_all, which never
    # alters existing tables. Postgres-only and idempotent.
    if bind.dialect.name == "postgresql":
        op.execute(
            "ALTER TABLE controls ADD COLUMN IF NOT EXISTS framework "
            "VARCHAR(48) NOT NULL DEFAULT 'ISO 27001:2022'"
        )


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
